import { ServiceLandingPage } from './service-landing.model';

const consult = { route: '/', fragment: 'consultation' };

export const MANAGED_IT_PAGE: ServiceLandingPage = {
  slug: 'managed-it',
  eyebrow: 'Managed IT services for GTA offices',
  title: 'Stabilize IT, reduce risk, and give staff one place to get help.',
  intro:
    'We take ownership of day-to-day support, Microsoft 365, endpoint security, backups, vendors, and office technology planning for small teams that cannot afford recurring IT chaos.',
  primaryCta: { label: 'Start a 30-Day IT Stabilization Plan', ...consult },
  secondaryCta: { label: 'Compare Service Areas', route: '/managed-it-services-vaughan' },
  trustChips: ['Security-first MSP', 'GTA local support', 'Built for 5-50 users'],
  heroVisual: {
    title: '90-day operating rhythm',
    metric: 'Support + security + planning',
    caption: 'A managed service model that moves from discovery to hardening, monitoring, documentation, and quarterly planning.',
    nodes: ['Helpdesk', 'Patching', 'Backups', 'Vendor control'],
  },
  handleTitle: 'Operational coverage that removes the usual IT blind spots',
  handleIntro:
    'The goal is not just faster tickets. It is a cleaner environment, fewer recurring disruptions, and leadership reporting that makes risk visible.',
  serviceCards: [
    { icon: 'bi-headset', title: 'Staff helpdesk', text: 'Remote-first support for everyday issues, with escalation paths for urgent business blockers.', outcome: 'Less staff downtime' },
    { icon: 'bi-shield-check', title: 'Endpoint protection', text: 'Device inventory, security tooling checks, encryption review, and patch hygiene.', outcome: 'Fewer avoidable incidents' },
    { icon: 'bi-microsoft', title: 'Microsoft 365 admin', text: 'User lifecycle, mailbox, Teams, SharePoint, MFA, and access policy administration.', outcome: 'Cleaner collaboration' },
    { icon: 'bi-database-check', title: 'Backup oversight', text: 'Backup monitoring, restore validation reminders, and recovery readiness notes.', outcome: 'More confidence after failure' },
    { icon: 'bi-router', title: 'Network coordination', text: 'Wi-Fi, ISP, printer, firewall, and vendor coordination when office connectivity is messy.', outcome: 'One accountable owner' },
    { icon: 'bi-person-lock', title: 'Onboarding and offboarding', text: 'Repeatable access changes for new hires, role changes, and departures.', outcome: 'Lower access risk' },
    { icon: 'bi-clipboard2-pulse', title: 'Monthly reporting', text: 'Open risks, resolved work, patch status, and recommendations summarized plainly.', outcome: 'Better decisions' },
    { icon: 'bi-signpost-split', title: 'Technology roadmap', text: 'A quarterly plan for upgrades, renewals, security improvements, and budget timing.', outcome: 'No surprise projects' },
  ],
  infographic: {
    eyebrow: 'Page-specific roadmap',
    title: '90-day stabilization roadmap',
    intro: 'Most offices need a structured reset before managed IT feels predictable. We prioritize risk and recurring pain first.',
    type: 'roadmap',
    items: [
      { label: 'Days 1-7', title: 'Discover', text: 'Inventory devices, admin access, vendors, backups, and current ticket patterns.' },
      { label: 'Days 8-21', title: 'Secure', text: 'Close urgent identity, patching, endpoint, and remote-access gaps.' },
      { label: 'Days 22-45', title: 'Stabilize', text: 'Put monitoring, alert handling, helpdesk routing, and vendor escalation in place.' },
      { label: 'Days 46-70', title: 'Document', text: 'Create runbooks, network notes, access standards, and asset records.' },
      { label: 'Days 71-90', title: 'Plan', text: 'Review trends, set quarterly priorities, and align improvements to budget.' },
    ],
  },
  problems: [
    { icon: 'bi-repeat', title: 'The same issues keep returning', text: 'Slow computers, printer problems, account lockouts, and Wi-Fi complaints never get root-caused.', outcome: 'We track patterns and fix the underlying configuration.' },
    { icon: 'bi-person-x', title: 'Departed staff still have access', text: 'Old accounts, shared passwords, and unclear ownership create quiet risk.', outcome: 'We standardize offboarding and privileged access review.' },
    { icon: 'bi-exclamation-triangle', title: 'No one knows what is backed up', text: 'Backups exist somewhere, but restore expectations are not documented.', outcome: 'We clarify coverage and recovery gaps before an outage.' },
  ],
  deliverables: [
    { icon: 'bi-file-earmark-text', title: 'IT environment summary', text: 'Devices, users, vendors, key systems, and known risks in one practical reference.' },
    { icon: 'bi-diagram-3', title: 'Network and access notes', text: 'Plain-language diagrams and admin access records your office can keep.' },
    { icon: 'bi-clipboard-check', title: 'Remediation backlog', text: 'Prioritized fixes with business impact, effort, and ownership.' },
    { icon: 'bi-bar-chart', title: 'Monthly service report', text: 'Completed work, open risks, patch posture, incidents, and recommendations.' },
    { icon: 'bi-journal-check', title: 'Runbooks', text: 'Repeatable procedures for onboarding, offboarding, outages, and vendor escalation.' },
    { icon: 'bi-calendar2-check', title: 'Quarterly roadmap', text: 'Budget-aware improvement plan tied to renewals, lifecycle, and security posture.' },
  ],
  engagement: [
    { title: 'Intake and access', text: 'We collect current vendors, systems, pain points, and admin access requirements.' },
    { title: 'Baseline review', text: 'We assess devices, identity, Microsoft 365, backups, network, and immediate risks.' },
    { title: 'Stabilization sprint', text: 'We clear priority risks and recurring user-facing blockers first.' },
    { title: 'Operate and report', text: 'Helpdesk, monitoring, patching, and monthly reporting move into a regular cadence.' },
    { title: 'Quarterly planning', text: 'We review trends and plan the next practical improvements with leadership.' },
  ],
  scenario: {
    title: 'Professional office with recurring disruption',
    problem: 'A 24-user office had weekly lockouts, slow laptops, printer issues, and no clear backup owner.',
    fix: 'We inventoried devices, cleaned Microsoft 365 access, standardized patching, documented vendors, and validated backup coverage.',
    outcome: 'Staff had one support path, leadership had a risk list, and recurring issues became measurable instead of anecdotal.',
  },
  faq: [
    { question: 'Do you replace our current IT vendor immediately?', answer: 'Not always. We can transition carefully, document what exists, and avoid breaking working systems during handoff.' },
    { question: 'Can you support remote and hybrid staff?', answer: 'Yes. The operating model covers remote helpdesk, device hygiene, identity controls, and secure access for hybrid teams.' },
    { question: 'Do you include cybersecurity?', answer: 'Security is part of the baseline: endpoint protection, MFA, patching, backup readiness, and access hygiene are reviewed from the start.' },
    { question: 'How quickly can support begin?', answer: 'Basic intake can begin quickly, but full stabilization depends on access, vendor cooperation, and the number of urgent risks discovered.' },
  ],
  relatedLinks: [
    { label: 'Managed IT Services Vaughan', route: '/managed-it-services-vaughan' },
    { label: 'Security Baseline Assessment', route: '/services/security-baseline-assessment' },
    { label: 'Microsoft 365 Support', route: '/microsoft-365' },
    { label: 'Cyber insurance readiness assessment', route: '/cyber-insurance-readiness-vaughan' },
  ],
  finalCta: {
    eyebrow: 'Stabilize the office',
    title: 'Get a managed IT plan that starts with risk, not just tickets.',
    text: 'Share your user count, locations, and top recurring issues. We will map the first 90 days.',
    primary: { label: 'Start My IT Stabilization Plan', ...consult },
    secondary: { label: 'Review Security Service', route: '/security-firewall' },
  },
};

export const SECURITY_FIREWALL_PAGE: ServiceLandingPage = {
  slug: 'security-firewall',
  eyebrow: 'Managed security and firewall operations',
  title: 'Reduce exposed attack paths without making work harder.',
  intro:
    'We manage practical layers of defense across firewall rules, remote access, endpoint detection, identity controls, patching, and recovery readiness for small offices.',
  primaryCta: { label: 'Book a Security Review', ...consult },
  secondaryCta: { label: 'Check Cyber Insurance Readiness', route: '/cyber-insurance-readiness-vaughan' },
  trustChips: ['Security-first', 'Huntress-aware operations', 'Remote access hardening'],
  heroVisual: {
    title: 'Layered defense model',
    metric: 'Identity to recovery',
    caption: 'Firewall policy is one layer. We connect edge, device, user, email, backup, and response controls into one operating model.',
    nodes: ['Firewall', 'Zero trust', 'Endpoints', 'Backups'],
  },
  handleTitle: 'Security controls that are operated, not just installed',
  handleIntro: 'Small offices need security that gets monitored, documented, tuned, and explained in business terms.',
  serviceCards: [
    { icon: 'bi-hdd-network', title: 'Firewall policy review', text: 'Rule cleanup, risky inbound exposure removal, VPN review, and edge device hygiene.', outcome: 'Smaller attack surface' },
    { icon: 'bi-diagram-3', title: 'Zero-trust access', text: 'Role-based remote access using device trust and least-privilege access paths.', outcome: 'Safer remote work' },
    { icon: 'bi-pc-display-horizontal', title: 'Endpoint detection', text: 'Coverage review, deployment coordination, alert triage, and response workflow.', outcome: 'Earlier detection' },
    { icon: 'bi-person-lock', title: 'Identity hardening', text: 'MFA, admin protection, risky sign-in review, and shared account cleanup.', outcome: 'Lower takeover risk' },
    { icon: 'bi-envelope-check', title: 'Email authentication', text: 'SPF, DKIM, DMARC, and phishing-exposure improvements for business email.', outcome: 'Fewer spoofing issues' },
    { icon: 'bi-bug', title: 'Vulnerability review', text: 'Quarterly scan review with priority, ownership, and practical remediation tracking.', outcome: 'Visible risk backlog' },
    { icon: 'bi-database-lock', title: 'Ransomware readiness', text: 'Backup, restore, access, and endpoint checks tied to incident impact.', outcome: 'Better recovery odds' },
    { icon: 'bi-telephone-forward', title: 'Incident escalation', text: 'Who to call, what to isolate, and how leadership gets updates during an event.', outcome: 'Less panic under pressure' },
  ],
  infographic: {
    eyebrow: 'Defense architecture',
    title: 'Layered defense architecture',
    intro: 'Each layer reduces a different type of business risk. The value comes from making the layers work together.',
    type: 'layers',
    items: [
      { title: 'Edge and remote access', text: 'Firewall rules, remote entry points, VPN replacement, and trusted device access.' },
      { title: 'Identity controls', text: 'MFA, privileged account review, conditional access, and risky sign-in handling.' },
      { title: 'Endpoint visibility', text: 'Detection coverage, alert workflow, patch posture, and device health signals.' },
      { title: 'Email and domain trust', text: 'Anti-spoofing records, phishing patterns, and mailbox protection review.' },
      { title: 'Recovery layer', text: 'Backup readiness, restore expectations, and incident communication runbooks.' },
    ],
  },
  problems: [
    { icon: 'bi-unlock', title: 'Old VPN exposes too much', text: 'Remote access lets users reach more systems than they need.', outcome: 'We replace broad access with role-based paths.' },
    { icon: 'bi-shield-exclamation', title: 'Alerts go nowhere', text: 'Security tools create noise but no clear response owner.', outcome: 'We define triage, escalation, and evidence capture.' },
    { icon: 'bi-person-badge', title: 'Admins use daily accounts', text: 'Privileged access is mixed with normal email and browsing.', outcome: 'We separate and protect high-impact accounts.' },
  ],
  deliverables: [
    { icon: 'bi-card-checklist', title: 'Firewall and exposure register', text: 'Risky services, remote access paths, policy gaps, and recommended cleanup.' },
    { icon: 'bi-diagram-2', title: 'Layered defense diagram', text: 'Visual map of edge, identity, endpoint, email, and recovery controls.' },
    { icon: 'bi-clipboard2-pulse', title: 'Security remediation plan', text: 'Prioritized fixes with owner, impact, and sequencing.' },
    { icon: 'bi-file-lock', title: 'Incident runbook', text: 'Containment, escalation, communication, and recovery steps for common incidents.' },
    { icon: 'bi-graph-up-arrow', title: 'Scan review summary', text: 'Quarterly vulnerability findings translated into practical action.' },
    { icon: 'bi-person-check', title: 'Access review notes', text: 'Admin accounts, shared access, service accounts, and remote access observations.' },
  ],
  engagement: [
    { title: 'Exposure intake', text: 'We review firewall model, remote access, endpoint count, SaaS stack, and urgent concerns.' },
    { title: 'Risk mapping', text: 'We identify the most likely paths an attacker or ransomware event would use.' },
    { title: 'Control rollout', text: 'We tune firewall, identity, endpoint, and backup controls in a staged order.' },
    { title: 'Response planning', text: 'We document escalation, containment, and recovery expectations.' },
    { title: 'Ongoing review', text: 'We revisit scan findings, new users, new devices, and policy drift.' },
  ],
  scenario: {
    title: 'Replacing exposed remote access',
    problem: 'A 22-user office relied on a legacy VPN with broad network access and no useful endpoint response path.',
    fix: 'We moved access to device-aware zero-trust paths, reviewed firewall rules, deployed endpoint coverage, and documented incident escalation.',
    outcome: 'Remote access stayed usable while exposed entry points and response confusion were reduced.',
  },
  faq: [
    { question: 'Is this only firewall management?', answer: 'No. Firewall policy matters, but we also address identity, endpoint, email, remote access, and recovery readiness.' },
    { question: 'Will security changes disrupt staff?', answer: 'We stage changes and explain the user impact before rollout, especially for MFA and remote access updates.' },
    { question: 'Can you help with cyber-insurance questions?', answer: 'We can identify technical blockers and evidence gaps, but we do not guarantee policy approval or coverage.' },
    { question: 'Do you respond to security alerts?', answer: 'We help define alert routing and response workflow based on the tools and service level in place.' },
  ],
  relatedLinks: [
    { label: 'Crisis Recovery', route: '/crisis-recovery' },
    { label: 'Security Baseline Assessment', route: '/services/security-baseline-assessment' },
    { label: 'Microsoft 365 Security Checklist', route: '/guides/security/microsoft-365-security/microsoft-365-checklist' },
    { label: 'Cyber insurance IT control review', route: '/cyber-insurance-readiness-vaughan' },
  ],
  finalCta: {
    eyebrow: 'Security review',
    title: 'Know which attack paths your office should close first.',
    text: 'Send your firewall model, remote access method, endpoint count, and biggest concern. We will map the priority risks.',
    primary: { label: 'Book a Security Review', ...consult },
    secondary: { label: 'Plan Crisis Recovery', route: '/crisis-recovery' },
  },
};

export const MICROSOFT_365_PAGE: ServiceLandingPage = {
  slug: 'microsoft-365',
  eyebrow: 'Microsoft 365 support and tenant hardening',
  title: 'Clean up Microsoft 365 before permissions, phishing, and lockouts slow the office.',
  intro:
    'We manage Exchange, Teams, SharePoint, OneDrive, Entra ID, MFA, Conditional Access, licensing, and backup coordination so collaboration stays secure and understandable.',
  primaryCta: { label: 'Request a Tenant Review', ...consult },
  secondaryCta: { label: 'Read the Security Checklist', route: '/guides/security/microsoft-365-security/microsoft-365-checklist' },
  trustChips: ['Tenant hardening', 'Plain-English governance', 'Built for growing teams'],
  heroVisual: {
    title: 'Tenant hardening map',
    metric: 'Identity + mail + data',
    caption: 'A practical view of the controls that protect staff accounts, inboxes, files, teams, and admin access.',
    nodes: ['MFA', 'Mail flow', 'SharePoint', 'Licensing'],
  },
  tenantHardening: {
    title: 'Microsoft 365 Tenant Hardening Map',
    metric: 'Interactive tenant controls',
    caption: 'A crawlable, practical map of the controls we review when hardening a Microsoft 365 tenant.',
    controls: [
      {
        key: 'entra-id',
        label: 'Entra ID',
        category: 'Identity',
        icon: 'bi-person-badge',
        description: 'Review users, roles, stale accounts, risky sign-ins, and admin access.',
        relatedKeys: ['mfa', 'conditional-access', 'licensing'],
        energy: 94,
        status: 'review',
        effort: '2–3 hrs',
        businessImpact: 'Stale accounts and over-privileged admins are the most common entry point in SMB breaches — one compromised admin account can expose the entire tenant.',
        tasks: [
          'Audit stale and inactive accounts',
          'Review admin role assignments',
          'Verify emergency access accounts',
          'Identify risky sign-in activity',
          'Review external and guest users',
          'Validate privileged account MFA',
        ],
        whatWeDo: 'MFA, admin roles, sign-in risk, device trust, and identity hygiene — reviewed as a complete picture rather than individual settings.',
        outcome: 'Lower account takeover risk',
        risk: 'Admin abuse',
        riskText: 'Privileged roles, sign-in conditions, and admin exceptions are tightened around real business needs, not convenience.',
        deliverable: 'Admin role matrix',
        deliverableText: 'Privileged accounts, role assignments, and recommended least-privilege changes documented in plain English.',
      },
      {
        key: 'mfa',
        label: 'MFA',
        category: 'Access',
        icon: 'bi-phone',
        description: 'Protect accounts with MFA rollout, exclusions review, and backup access planning.',
        relatedKeys: ['entra-id', 'conditional-access', 'backup'],
        energy: 91,
        status: 'hardened',
        effort: '1–2 hrs',
        businessImpact: 'Accounts without MFA are 99% more likely to be compromised — even a weak password becomes low-risk when a second factor is in place.',
        tasks: [
          'Confirm MFA enrollment for all users',
          'Review break-glass account exclusions',
          'Verify phishing-resistant MFA for admins',
          'Test backup authentication methods',
          'Document MFA recovery procedures',
        ],
        whatWeDo: 'MFA rollout, exclusions review, and backup access planning — so all users are protected without creating self-inflicted lockouts.',
        outcome: 'Fewer self-inflicted lockouts',
        risk: 'Lockouts',
        riskText: 'Emergency access, exclusion management, and staged rollout planning help prevent the most common MFA-related disruptions.',
        deliverable: 'MFA and access policy set',
        deliverableText: 'Baseline MFA policies and exclusion exceptions documented with owner and review date.',
      },
      {
        key: 'conditional-access',
        label: 'Conditional Access',
        category: 'Access',
        icon: 'bi-signpost-split',
        description: 'Control sign-ins by device, location, risk, and role.',
        relatedKeys: ['entra-id', 'mfa', 'teams'],
        energy: 86,
        status: 'review',
        effort: '2–4 hrs',
        businessImpact: 'Without Conditional Access policies, a stolen password from any device or location is an open door — sign-in rules are what make MFA enforceable.',
        tasks: [
          'Audit all policies for coverage gaps',
          'Check overly broad policy exclusions',
          'Test sign-in by device and location',
          'Align policies to user role and risk',
          'Review legacy authentication blocks',
        ],
        whatWeDo: 'Policies tuned to role, location, device state, and risk — without locking out normal business activity or creating friction for regular users.',
        outcome: 'Better access control with fewer surprises',
        risk: 'Policy gaps',
        riskText: 'Overly broad exclusions and missing coverage by device or location leave sign-in doors open that should be controlled.',
        deliverable: 'CA policy summary',
        deliverableText: 'Conditional Access policy map with gaps, exclusions, and plain-English rationale for each rule.',
      },
      {
        key: 'exchange',
        label: 'Exchange',
        category: 'Mail',
        icon: 'bi-envelope-check',
        description: 'Harden mail flow, phishing controls, SPF/DKIM/DMARC, and forwarding rules.',
        relatedKeys: ['mfa', 'backup'],
        energy: 88,
        status: 'hardened',
        effort: '2–3 hrs',
        businessImpact: 'Email is the top attack vector for small offices — misconfigured SPF/DKIM/DMARC and unchecked forwarding rules are the two most common gaps we find.',
        tasks: [
          'Verify SPF, DKIM, and DMARC records',
          'Audit mailbox forwarding and redirects',
          'Review anti-phishing policy settings',
          'Check shared mailbox access rights',
          'Inspect risky transport rules',
        ],
        whatWeDo: 'Mail flow rules, mailbox settings, anti-spoofing records, shared mailbox hygiene, and delivery anomalies reviewed and corrected.',
        outcome: 'Cleaner email operations',
        risk: 'Phishing',
        riskText: 'Domain authentication records and mailbox controls reduce the impact of credential theft and spoofed mail reaching staff inboxes.',
        deliverable: 'Mail security summary',
        deliverableText: 'Domain authentication posture, phishing control gaps, and risky transport or forwarding rules.',
      },
      {
        key: 'sharepoint',
        label: 'SharePoint',
        category: 'Collaboration',
        icon: 'bi-diagram-3',
        description: 'Review external sharing, site permissions, and sensitive file exposure.',
        relatedKeys: ['onedrive', 'teams', 'backup'],
        energy: 78,
        status: 'review',
        effort: '3–4 hrs',
        businessImpact: 'A single broadly-shared folder can expose sensitive client or financial files to dozens of people outside your intended audience — often without anyone noticing.',
        tasks: [
          'Map external sharing permissions',
          'Review sensitive site access',
          'Identify abandoned or orphaned sites',
          'Check default link sharing type',
          'Audit guest access expiry settings',
        ],
        whatWeDo: 'Site structure, sharing defaults, permission cleanup, and sensitive data exposure — reviewed so files stay where they should and nothing leaks quietly.',
        outcome: 'Files are easier to control',
        risk: 'Oversharing',
        riskText: 'External links, guest access, and inherited permissions are reviewed before sensitive folders drift to people who should not have them.',
        deliverable: 'Sharing cleanup notes',
        deliverableText: 'SharePoint site permissions, guest access exposure, and sharing link risk mapped with recommended tightening steps.',
      },
      {
        key: 'onedrive',
        label: 'OneDrive',
        category: 'Collaboration',
        icon: 'bi-cloud-check',
        description: 'Clean up sharing links, sync risks, and user-level access.',
        relatedKeys: ['sharepoint', 'teams', 'backup'],
        energy: 72,
        status: 'review',
        effort: '1–2 hrs',
        businessImpact: 'Personal drives are the least-managed part of most Microsoft 365 tenants — public sharing links created years ago are frequently still active and forgotten.',
        tasks: [
          'Review sharing link defaults',
          'Check sync client restrictions',
          'Identify broad public link exposure',
          'Audit known folder move status',
          'Review B2B sharing policies',
        ],
        whatWeDo: 'Sharing link cleanup, sync configuration, and user-level access review — so personal and shared drives are not silent exposure points.',
        outcome: 'Reduced file exposure',
        risk: 'Oversharing',
        riskText: 'Personal drives often accumulate public links and stale shares that give far more access than intended.',
        deliverable: 'OneDrive sharing report',
        deliverableText: 'Public and broad sharing link inventory with remediation priority and recommended link policy settings.',
      },
      {
        key: 'teams',
        label: 'Teams',
        category: 'Collaboration',
        icon: 'bi-people',
        description: 'Review guest access, Teams sprawl, meeting controls, and file permissions.',
        relatedKeys: ['sharepoint', 'onedrive', 'conditional-access'],
        energy: 68,
        status: 'planned',
        effort: '2–3 hrs',
        businessImpact: 'Guest access in Teams often gives external contacts more file visibility than anyone intended — abandoned channels and unchecked guests are a quiet exposure risk.',
        tasks: [
          'Audit guest access policies',
          'Review meeting recording defaults',
          'Check external federation settings',
          'Identify abandoned or unused teams',
          'Review private channel ownership',
        ],
        whatWeDo: 'Guest access settings, meeting defaults, channel hygiene, and ownership expectations — so collaboration tools do not quietly open the network to outsiders.',
        outcome: 'Less collaboration sprawl',
        risk: 'Collaboration sprawl',
        riskText: 'Unchecked guest access and abandoned teams gradually expose files and channels to people who should no longer have access.',
        deliverable: 'Teams governance summary',
        deliverableText: 'Guest access exposure, abandoned teams inventory, and ownership gaps with recommended governance defaults.',
      },
      {
        key: 'licensing',
        label: 'Licensing',
        category: 'Cost control',
        icon: 'bi-credit-card-2-front',
        description: 'Remove waste, align licenses to actual user needs, and avoid overspend.',
        relatedKeys: ['entra-id', 'teams'],
        energy: 58,
        status: 'planned',
        effort: '1–2 hrs',
        businessImpact: 'Most small offices are paying for 20–30% more licenses than they actively use — a quick audit typically surfaces savings and clears up overlapping subscriptions.',
        tasks: [
          'Identify unassigned license seats',
          'Match licenses to actual user roles',
          'Flag overlapping capability plans',
          'Review upcoming renewal dates',
          'Audit shared device license use',
        ],
        whatWeDo: 'License assignment audit, cost review, and entitlement cleanup — so the tenant is not paying for seats that go unused or features that overlap.',
        outcome: 'Reduced license waste',
        risk: 'Cost overrun',
        riskText: 'Unassigned seats and overlapping plans create ongoing spend on capabilities the office is not actually using.',
        deliverable: 'License review report',
        deliverableText: 'Unused, over-assigned, and mismatched licenses with reallocation suggestions and renewal dates.',
      },
      {
        key: 'backup',
        label: 'Backup',
        category: 'Recovery',
        icon: 'bi-database-check',
        description: 'Coordinate Microsoft 365 backup planning for mail, files, and recovery.',
        relatedKeys: ['exchange', 'sharepoint', 'onedrive', 'mfa'],
        energy: 82,
        status: 'review',
        effort: '1–2 hrs',
        businessImpact: "Microsoft's retention policies are not a backup — deleted emails and files can be permanently lost if a third-party backup is not configured, tested, and verified.",
        tasks: [
          'Confirm backup coverage scope',
          'Review retention policy settings',
          'Verify restore access and procedures',
          'Document recovery time expectations',
          'Check admin access to backup console',
        ],
        whatWeDo: 'Microsoft 365 backup expectations, vendor coverage checks, and restore evidence review — so the office knows exactly what is recoverable and by when.',
        outcome: 'Clear recovery assumptions',
        risk: 'Recovery gaps',
        riskText: 'Retention policies are not the same as backups. We separate the two and map what is actually restorable if mail or files are deleted.',
        deliverable: 'Backup coverage summary',
        deliverableText: 'Backup scope, retention vs. restore distinction, recovery time expectations, and vendor access verification.',
      },
    ],
  },
  riskControlMap: [
    {
      risk: 'Phishing',
      controls: 'Exchange + MFA',
      icon: 'bi-envelope-exclamation',
      text: 'Mailbox policy, domain authentication, and MFA reduce the impact of stolen credentials and spoofed mail.',
    },
    {
      risk: 'Lockouts',
      controls: 'Entra ID + MFA',
      icon: 'bi-key',
      text: 'Emergency access, exclusions, and staged rollout planning help prevent self-inflicted access failures.',
    },
    {
      risk: 'Oversharing',
      controls: 'SharePoint + OneDrive',
      icon: 'bi-share',
      text: 'External links, guest access, and inherited permissions are reviewed before sensitive files drift.',
    },
    {
      risk: 'Admin abuse',
      controls: 'Entra ID + Conditional Access',
      icon: 'bi-person-lock',
      text: 'Privileged roles, sign-in conditions, and admin exceptions are tightened around real business needs.',
    },
    {
      risk: 'Recovery gaps',
      controls: 'Backup',
      icon: 'bi-arrow-counterclockwise',
      text: 'Retention assumptions are separated from recoverable backup so mail and files have a practical restore path.',
    },
  ],
  handleTitle: 'Microsoft 365 operations that keep collaboration controlled',
  handleIntro: 'Most tenant problems are not Microsoft outages. They are permission drift, weak account controls, and unclear admin habits.',
  serviceCards: [
    { icon: 'bi-envelope-check', title: 'Exchange Online', text: 'Mail flow, mailbox settings, anti-spoofing records, shared mailboxes, and delivery issues.', outcome: 'Cleaner email operations' },
    { icon: 'bi-people', title: 'Teams governance', text: 'Guest access, meeting defaults, channel hygiene, and ownership expectations.', outcome: 'Less collaboration sprawl' },
    { icon: 'bi-folder-symlink', title: 'SharePoint and OneDrive', text: 'Site structure, sharing settings, permission cleanup, and sensitive data locations.', outcome: 'Files are easier to control' },
    { icon: 'bi-person-lock', title: 'Entra ID security', text: 'MFA, admin roles, sign-in risk, device trust, and identity hygiene.', outcome: 'Lower account takeover risk' },
    { icon: 'bi-signpost-split', title: 'Conditional Access', text: 'Policies tuned to role, location, device, and risk without locking out normal work.', outcome: 'Better control with fewer surprises' },
    { icon: 'bi-credit-card-2-front', title: 'License management', text: 'License assignment standards, cost review, and entitlement cleanup.', outcome: 'Reduced waste' },
    { icon: 'bi-arrow-left-right', title: 'Joiner-mover-leaver', text: 'Repeatable user lifecycle changes for onboarding, role changes, and offboarding.', outcome: 'Fewer missed steps' },
    { icon: 'bi-database-check', title: 'Backup coordination', text: 'Microsoft 365 backup expectations, vendor checks, and restore evidence review.', outcome: 'Clear recovery assumptions' },
  ],
  infographic: {
    eyebrow: 'Tenant hardening map',
    title: 'Microsoft 365 tenant hardening map',
    intro: 'We organize the tenant around the controls that matter most to a small business: identity, email, data, devices, and recovery.',
    type: 'map',
    items: [
      { title: 'Identity core', text: 'MFA, admin roles, risky sign-ins, password reset, and emergency access.' },
      { title: 'Mail protection', text: 'SPF, DKIM, DMARC, anti-phishing settings, transport rules, and shared mailbox hygiene.' },
      { title: 'Collaboration boundaries', text: 'Teams guest access, SharePoint sharing, external links, and site ownership.' },
      { title: 'Device and app trust', text: 'Conditional Access rules that consider device state and user role.' },
      { title: 'Backup and audit evidence', text: 'Retention expectations, backup coverage, restore proof, and admin change traceability.' },
    ],
  },
  problems: [
    { icon: 'bi-key', title: 'Too many global admins', text: 'Admin roles accumulate because no one wants to risk breaking access.', outcome: 'We reduce privilege and document exceptions.' },
    { icon: 'bi-share', title: 'Files are shared everywhere', text: 'External links and inherited permissions make sensitive folders hard to govern.', outcome: 'We map and tighten sharing rules.' },
    { icon: 'bi-envelope-exclamation', title: 'Phishing keeps getting through', text: 'Authentication records and mailbox rules are incomplete or inconsistent.', outcome: 'We improve domain trust and mail controls.' },
  ],
  deliverables: [
    { icon: 'bi-person-vcard', title: 'Admin role matrix', text: 'Privileged accounts, role assignments, and recommended least-privilege changes.' },
    { icon: 'bi-shield-lock', title: 'MFA and access policy set', text: 'Baseline policies and exceptions documented in plain English.' },
    { icon: 'bi-folder-check', title: 'Sharing cleanup notes', text: 'SharePoint, OneDrive, Teams, and guest access observations.' },
    { icon: 'bi-envelope-paper', title: 'Mail security summary', text: 'Domain authentication, phishing controls, and risky mailbox rules.' },
    { icon: 'bi-currency-dollar', title: 'License review', text: 'Unused, over-assigned, or mismatched licenses with cleanup suggestions.' },
    { icon: 'bi-journal-code', title: 'Tenant runbook', text: 'Repeatable admin procedures for user changes, groups, and access requests.' },
  ],
  engagement: [
    { title: 'Tenant intake', text: 'We review user count, licensing, known issues, admin access, and security goals.' },
    { title: 'Policy and permission review', text: 'We inspect identity, mail, sharing, admin roles, and backup assumptions.' },
    { title: 'Priority fixes', text: 'We address lockouts, exposed admins, risky sharing, and mail issues first.' },
    { title: 'Governance setup', text: 'We document rules for users, guests, groups, sites, and license assignment.' },
    { title: 'Ongoing administration', text: 'We manage changes and watch for drift as your team grows.' },
  ],
  scenario: {
    title: 'Tenant drift after fast growth',
    clientType: 'Professional services · 35 staff · Vaughan',
    problem: 'Inconsistent MFA, unmanaged Teams guests, too many admin accounts, and rising license costs — accumulated over two years of fast hiring.',
    fix: 'We mapped roles, staged Conditional Access, cleaned guest settings, reviewed sharing defaults, and standardized license assignment across all departments.',
    outcome: 'Leadership could see the tenant rules clearly, staff kept collaborating without disruption, and risky exceptions were reduced to zero.',
  },
  faq: [
    { question: 'Can you fix Microsoft 365 without disrupting email?', answer: 'Yes. Risky changes are staged and tested, especially mail flow, MFA, and Conditional Access policies.' },
    { question: 'Do you handle SharePoint structure?', answer: 'We help clean permissions, sharing rules, ownership, and practical site organization for small teams.' },
    { question: 'Can you reduce licensing cost?', answer: 'We review assignment patterns and unused entitlements, then recommend cleanup where it will not remove needed features.' },
    { question: 'Do we need Microsoft 365 backup?', answer: 'Many offices should evaluate it. We clarify what Microsoft retains, what backup vendors cover, and what restore proof exists.' },
  ],
  relatedLinks: [
    { label: 'Managed IT Services', route: '/managed-it-services' },
    { label: 'MFA Rollout Guide', route: '/guides/security/microsoft-365-security/mfa-rollout-small-business' },
    { label: 'Security and Firewall', route: '/security-firewall' },
    { label: 'Cyber insurance readiness support', route: '/cyber-insurance-readiness-vaughan' },
  ],
  finalCta: {
    eyebrow: 'Tenant review',
    title: 'Turn Microsoft 365 from a messy admin portal into a controlled workspace.',
    text: 'Share your user count, license mix, and top account or collaboration issue. We will identify the cleanest first fixes.',
    primary: { label: 'Request a Tenant Review', ...consult },
    secondary: { label: 'View Microsoft 365 Checklist', route: '/guides/security/microsoft-365-security/microsoft-365-checklist' },
  },
};

export const GOOGLE_WORKSPACE_PAGE: ServiceLandingPage = {
  slug: 'google-workspace',
  eyebrow: 'Google Workspace support for small business',
  title: 'Secure and manage Google Workspace before access sprawl slows the office.',
  intro:
    'We help small teams set up, migrate, secure, and administer Gmail, Drive, Shared Drives, Meet, admin roles, device access, and recovery workflows so Google Workspace stays reliable as the business grows.',
  primaryCta: { label: 'Request a Workspace Review', ...consult },
  secondaryCta: { label: 'Compare Managed IT', route: '/managed-it-services' },
  trustChips: ['Gmail and Drive administration', 'Security-first setup', 'Built for 5-50 users'],
  heroVisual: {
    title: 'Workspace control map',
    metric: 'Identity + sharing + recovery',
    caption: 'A practical admin model for the controls that affect account safety, file access, email trust, and staff support.',
    nodes: ['Gmail', 'Drive', 'MFA', 'Recovery'],
  },
  handleTitle: 'Google Workspace administration that keeps access understandable',
  handleIntro:
    'Most Workspace problems are small at first: shared passwords, loose Drive links, old users, weak admin roles, and no clear owner for recovery. We clean those up before they become business interruptions.',
  serviceCards: [
    { icon: 'bi-google', title: 'Workspace setup', text: 'Domain, user, group, Gmail, Drive, Meet, and admin-console settings configured around how the office actually works.', outcome: 'Cleaner launch or reset' },
    { icon: 'bi-person-lock', title: '2-step verification and admin roles', text: 'MFA enforcement, admin role review, break-glass planning, and exception cleanup for high-risk accounts.', outcome: 'Lower takeover risk' },
    { icon: 'bi-folder-check', title: 'Shared Drive governance', text: 'Drive structure, ownership, external sharing, link settings, and access review so sensitive folders do not drift.', outcome: 'Safer collaboration' },
    { icon: 'bi-envelope-check', title: 'Gmail security', text: 'SPF, DKIM, DMARC, suspicious routing checks, phishing controls, and mailbox hygiene review.', outcome: 'More trusted email' },
    { icon: 'bi-phone-lock', title: 'Device access controls', text: 'Browser, mobile, and endpoint access settings reviewed for practical control without blocking normal work.', outcome: 'Better access boundaries' },
    { icon: 'bi-arrow-left-right', title: 'Migration support', text: 'Mailbox, file, calendar, group, and cutover planning for teams moving into or reorganizing Google Workspace.', outcome: 'Less migration chaos' },
    { icon: 'bi-person-check', title: 'Onboarding and offboarding', text: 'Repeatable user lifecycle steps for new hires, role changes, aliases, groups, and departing staff.', outcome: 'Fewer missed access changes' },
    { icon: 'bi-database-check', title: 'Backup and recovery review', text: 'Recovery options, admin recovery, retention expectations, and third-party backup considerations documented plainly.', outcome: 'Clearer recovery assumptions' },
  ],
  infographic: {
    eyebrow: 'Workspace operating model',
    title: 'Google Workspace operating model',
    intro: 'We organize support around the decisions that most often create risk or staff friction in a small business tenant.',
    type: 'map',
    items: [
      { title: 'Identity and admins', text: 'MFA, admin roles, account recovery, aliases, groups, and user lifecycle.' },
      { title: 'Email trust', text: 'Gmail routing, spoofing protection, SPF, DKIM, DMARC, and phishing exposure.' },
      { title: 'Drive and sharing', text: 'Shared Drives, external links, folder ownership, guest access, and sensitive file locations.' },
      { title: 'Devices and access', text: 'Managed browser or mobile access, sign-in controls, and practical device expectations.' },
      { title: 'Recovery and continuity', text: 'Retention, account recovery, backup assumptions, and administrator runbooks.' },
    ],
  },
  problems: [
    { icon: 'bi-share', title: 'Files are shared too broadly', text: 'Old external links, personal My Drive ownership, and unmanaged Shared Drives make sensitive data hard to control.', outcome: 'We map sharing risk and tighten the highest-impact settings first.' },
    { icon: 'bi-person-x', title: 'Departed staff still own access', text: 'Former users may retain groups, files, aliases, recovery methods, or delegated mailbox access.', outcome: 'We standardize offboarding and ownership transfer.' },
    { icon: 'bi-envelope-exclamation', title: 'Phishing and spoofing keep reaching staff', text: 'Missing DNS authentication and weak mailbox rules can make Gmail harder to trust.', outcome: 'We improve email authentication and review risky rules.' },
  ],
  deliverables: [
    { icon: 'bi-card-checklist', title: 'Workspace admin baseline', text: 'Plain-English summary of users, groups, admins, MFA coverage, sharing settings, and urgent risks.' },
    { icon: 'bi-folder-symlink', title: 'Drive access findings', text: 'Shared Drive ownership, external sharing, high-risk folders, and cleanup recommendations.' },
    { icon: 'bi-envelope-paper', title: 'Email security summary', text: 'SPF, DKIM, DMARC, routing, aliases, groups, and phishing-control observations.' },
    { icon: 'bi-arrow-repeat', title: 'Migration or cleanup plan', text: 'Sequenced changes for setup, migration, restructuring, or tenant stabilization.' },
    { icon: 'bi-journal-check', title: 'Admin runbook', text: 'Repeatable procedures for onboarding, offboarding, recovery, and permission changes.' },
    { icon: 'bi-shield-check', title: 'Security improvement backlog', text: 'Prioritized fixes tied to business impact, staff friction, and risk.' },
  ],
  engagement: [
    { title: 'Workspace intake', text: 'We collect user count, domains, current pain points, admin access, and migration or cleanup goals.' },
    { title: 'Tenant review', text: 'We inspect identity, admin roles, Gmail, Drive, sharing, devices, DNS records, and recovery settings.' },
    { title: 'Priority fixes', text: 'We address urgent access, sharing, phishing, and recovery risks before lower-impact cleanup.' },
    { title: 'Migration or governance work', text: 'We stage file, mailbox, group, and policy changes so staff can keep working.' },
    { title: 'Ongoing administration', text: 'We handle user changes, permissions, support tickets, and periodic security review as part of managed IT.' },
  ],
  scenario: {
    title: 'Growing office with messy Drive access',
    problem: 'A 19-user office had client folders owned by former staff, public links that no one reviewed, inconsistent 2-step verification, and no clear recovery process.',
    fix: 'We reviewed admin roles, enforced MFA in stages, reorganized Shared Drives, cleaned external links, updated SPF/DKIM/DMARC, and documented onboarding and offboarding steps.',
    outcome: 'Staff kept Gmail and Drive workflows, leadership gained visibility into sharing risk, and account changes became repeatable instead of improvised.',
  },
  faq: [
    { question: 'Do you support Google Workspace for small businesses?', answer: 'Yes. We support setup, administration, security review, migrations, user changes, Gmail, Drive, Shared Drives, and account recovery for small teams.' },
    { question: 'Can you migrate us from another email platform?', answer: 'Yes. We plan mailbox, calendar, contact, file, DNS, and cutover steps before making changes so the migration is controlled.' },
    { question: 'Is Google Workspace backup included?', answer: 'Google retention and admin recovery are not the same as a full backup strategy. We review recovery expectations and recommend third-party backup where the business risk justifies it.' },
    { question: 'Can you help if we also use Microsoft 365?', answer: 'Yes. Some small businesses use both. We help define which platform owns email, files, identity, and device access so support does not become confusing.' },
  ],
  relatedLinks: [
    { label: 'Managed IT Services', route: '/managed-it-services' },
    { label: 'Cybersecurity Services Vaughan', route: '/cybersecurity-services-vaughan' },
    { label: 'Security and Firewall', route: '/security-firewall' },
    { label: 'Small Business Cybersecurity Guides', route: '/guides/security' },
    { label: 'Phishing Protection Guide', route: '/guides/security/microsoft-365-security/phishing-protection' },
  ],
  finalCta: {
    eyebrow: 'Workspace review',
    title: 'Get Google Workspace under control before access and sharing drift further.',
    text: 'Share your user count, domains, and top Gmail or Drive issue. We will map the highest-value cleanup path.',
    primary: { label: 'Request a Workspace Review', ...consult },
    secondary: { label: 'Review Security Baseline', route: '/services/security-baseline-assessment' },
  },
};

export const MEDICAL_CLINIC_IT_PAGE: ServiceLandingPage = {
  slug: 'medical-clinic-it',
  eyebrow: 'Managed IT for medical clinics in Vaughan',
  title: 'Keep clinic workstations, email, Wi-Fi, and recovery ready for patient-facing days.',
  intro:
    'We support Vaughan medical clinics that need stable front-desk systems, secure Microsoft 365, endpoint protection, clinic Wi-Fi, backup readiness, vendor coordination, and practical privacy-aware operations without making compliance guarantees.',
  primaryCta: { label: 'Book a Clinic IT Assessment', ...consult },
  secondaryCta: { label: 'Run a Security Baseline', route: '/services/security-baseline-assessment' },
  trustChips: ['Clinic workflow aware', 'Endpoint and backup focus', 'Vaughan local support'],
  heroVisual: {
    title: 'Clinic IT control map',
    metric: 'Front desk + providers + recovery',
    caption: 'A clinic support model that connects workstations, Microsoft 365, Wi-Fi, vendors, backups, and security controls.',
    nodes: ['Front desk', 'M365', 'Wi-Fi', 'Backups'],
  },
  handleTitle: 'Clinic-specific IT support for the systems that interrupt patient flow',
  handleIntro:
    'Medical offices cannot treat IT as a generic helpdesk. A slow workstation, locked mailbox, unstable Wi-Fi, or missing backup path can affect booking, check-in, billing, and provider schedules.',
  serviceCards: [
    { icon: 'bi-pc-display', title: 'Front-desk and exam-room workstations', text: 'Device setup, patching, performance cleanup, replacement planning, and support for shared-use clinic stations.', outcome: 'Less appointment disruption' },
    { icon: 'bi-microsoft', title: 'Microsoft 365 and secure email', text: 'Mailbox, Teams, SharePoint, MFA, anti-spoofing records, and account recovery support for clinic teams.', outcome: 'Safer communication' },
    { icon: 'bi-shield-check', title: 'Endpoint protection', text: 'Managed endpoint protection, patch posture review, suspicious activity escalation, and device health monitoring.', outcome: 'Earlier risk visibility' },
    { icon: 'bi-wifi', title: 'Clinic Wi-Fi and network separation', text: 'Staff, guest, device, and vendor network review so patient Wi-Fi and business systems are not casually mixed.', outcome: 'Cleaner network boundaries' },
    { icon: 'bi-database-check', title: 'Backup and recovery readiness', text: 'Backup coverage review, restore expectations, recovery contacts, and continuity notes for critical clinic workflows.', outcome: 'Clearer downtime plan' },
    { icon: 'bi-person-lock', title: 'Access lifecycle', text: 'Onboarding, role changes, offboarding, MFA reset, shared account cleanup, and admin access review.', outcome: 'Fewer access gaps' },
    { icon: 'bi-router', title: 'Vendor coordination', text: 'Coordination with EMR, billing, phone, internet, printer, scanner, and clinical software vendors.', outcome: 'One IT owner' },
    { icon: 'bi-clipboard2-pulse', title: 'Security readiness reporting', text: 'Plain-language risk notes for leadership review without claiming legal or regulatory certification.', outcome: 'Better decisions' },
  ],
  infographic: {
    eyebrow: 'Clinic stabilization plan',
    title: 'Clinic IT stabilization plan',
    intro: 'We prioritize the systems that most directly affect appointments, patient communication, staff access, and recovery.',
    type: 'ops',
    items: [
      { title: 'Patient-facing workflow', text: 'Front-desk devices, printers, scanners, phones, and appointment-critical access.' },
      { title: 'Identity and email', text: 'MFA, mailbox security, admin roles, shared mailboxes, and phishing exposure.' },
      { title: 'Endpoint and patching', text: 'Workstations, laptops, shared stations, patch cadence, and protection status.' },
      { title: 'Network reliability', text: 'Clinic Wi-Fi, guest access, ISP handoff, segmentation, and vendor devices.' },
      { title: 'Backup and recovery', text: 'Restore expectations, business-critical systems, recovery contacts, and evidence of recent checks.' },
    ],
  },
  problems: [
    { icon: 'bi-clock-history', title: 'Slow workstations delay appointments', text: 'Aging PCs, patch failures, and overloaded shared devices slow check-in and provider workflows.', outcome: 'We standardize, patch, and plan replacement before disruption repeats.' },
    { icon: 'bi-envelope-exclamation', title: 'Email phishing targets clinic staff', text: 'Booking, billing, vendor, and patient communication patterns are easy for attackers to imitate.', outcome: 'We harden Microsoft 365 and train controls around real clinic workflows.' },
    { icon: 'bi-wifi-off', title: 'Clinic Wi-Fi mixes too many devices', text: 'Guest phones, staff laptops, printers, scanners, and vendor devices often share networks they should not.', outcome: 'We separate access where it improves stability and risk.' },
  ],
  deliverables: [
    { icon: 'bi-list-check', title: 'Clinic IT baseline', text: 'Inventory of users, devices, Microsoft 365, network, vendors, backups, and priority risks.' },
    { icon: 'bi-shield-lock', title: 'Security readiness notes', text: 'MFA, endpoint protection, email authentication, admin access, and backup observations.' },
    { icon: 'bi-diagram-3', title: 'Workflow dependency map', text: 'Front desk, provider, billing, phone, internet, printer, and vendor dependencies documented.' },
    { icon: 'bi-database-up', title: 'Backup and recovery summary', text: 'What appears covered, what needs confirmation, and which restore assumptions need testing.' },
    { icon: 'bi-journal-check', title: 'Clinic support runbook', text: 'Repeatable steps for onboarding, offboarding, outages, vendor calls, and urgent support.' },
    { icon: 'bi-clipboard-check', title: 'Remediation backlog', text: 'Prioritized fixes with business impact, urgency, and next-step ownership.' },
  ],
  engagement: [
    { title: 'Clinic intake', text: 'We collect provider count, staff count, device count, vendors, recurring issues, and critical workflows.' },
    { title: 'Baseline review', text: 'We assess workstations, Microsoft 365, endpoint protection, backups, Wi-Fi, admin access, and vendor dependencies.' },
    { title: 'Stabilization sprint', text: 'We address recurring support blockers, security basics, access gaps, and backup uncertainty first.' },
    { title: 'Documentation and handoff', text: 'We produce a clinic-specific support map that leadership and staff can actually use.' },
    { title: 'Ongoing managed IT', text: 'We provide helpdesk, monitoring, patching, vendor coordination, and recurring security review.' },
  ],
  scenario: {
    title: 'Clinic with recurring front-desk disruption',
    problem: 'A Vaughan clinic had slow shared workstations, inconsistent MFA, unclear backup ownership, printer issues, and Wi-Fi complaints during busy booking periods.',
    fix: 'We reviewed devices, Microsoft 365 access, endpoint protection, Wi-Fi separation, backup coverage, and vendor contacts, then sequenced fixes around clinic hours.',
    outcome: 'The clinic gained a practical support path, fewer repeated disruptions, and clearer security and recovery priorities.',
  },
  faq: [
    { question: 'Do you guarantee PHIPA compliance?', answer: 'No. We do not make legal compliance guarantees. We help implement practical privacy-aware IT controls, documentation, access hygiene, endpoint protection, and backup readiness that support clinic risk reduction.' },
    { question: 'Can you support EMR or billing vendors?', answer: 'We coordinate with clinic software vendors, internet providers, phone providers, printer vendors, and EMR or billing support teams so the clinic has one technical owner during troubleshooting.' },
    { question: 'Can you secure Microsoft 365 for a medical clinic?', answer: 'Yes. We review MFA, admin roles, mailbox security, anti-spoofing DNS records, sharing settings, and account recovery so clinic email and collaboration are better controlled.' },
    { question: 'Do clinics need endpoint protection?', answer: 'Yes. Shared workstations and staff laptops should have managed endpoint protection, patching, and a response path when suspicious activity appears.' },
  ],
  relatedLinks: [
    { label: 'Managed IT Services', route: '/managed-it-services' },
    { label: 'Cybersecurity Services Vaughan', route: '/cybersecurity-services-vaughan' },
    { label: 'Microsoft 365 Support', route: '/microsoft-365' },
    { label: 'Security and Firewall', route: '/security-firewall' },
    { label: 'Security Baseline Assessment', route: '/services/security-baseline-assessment' },
    { label: 'Free Security Assessment', route: '/free-security-assessment' },
  ],
  finalCta: {
    eyebrow: 'Clinic IT assessment',
    title: 'Build a clinic IT plan around uptime, access, security, and recovery.',
    text: 'Share your clinic size, systems, vendors, and top recurring IT issue. We will map the first stabilization steps.',
    primary: { label: 'Book a Clinic IT Assessment', ...consult },
    secondary: { label: 'Start Security Baseline', route: '/services/security-baseline-assessment' },
  },
};

export const AWS_INFRASTRUCTURE_PAGE: ServiceLandingPage = {
  slug: 'aws-infrastructure',
  eyebrow: 'Secure AWS infrastructure operations',
  title: 'Make AWS reliable, documented, and easier to operate.',
  intro:
    'We help small teams run AWS workloads with cleaner IAM, safer networking, monitored backups, cost guardrails, and runbooks that make cloud operations less dependent on guesswork.',
  primaryCta: { label: 'Request an AWS Assessment', ...consult },
  secondaryCta: { label: 'Add Security Monitoring', route: '/security-firewall' },
  trustChips: ['Cloud security', 'Cost governance', 'Runbook-driven operations'],
  heroVisual: {
    title: 'Secure cloud operations model',
    metric: 'IAM + VPC + backup + cost',
    caption: 'A cloud support model focused on visibility, least privilege, recovery confidence, and predictable spend.',
    nodes: ['IAM', 'VPC', 'CloudWatch', 'Budgets'],
  },
  handleTitle: 'AWS foundations that reduce operational surprises',
  handleIntro: 'Cloud complexity builds slowly. We make the account model, access, monitoring, backup, and cost controls easier to understand and operate.',
  serviceCards: [
    { icon: 'bi-person-lock', title: 'IAM hardening', text: 'Least-privilege review, admin path cleanup, MFA, and service account notes.', outcome: 'Reduced blast radius' },
    { icon: 'bi-diagram-3', title: 'VPC segmentation', text: 'Network layout, security groups, subnet boundaries, and exposed service review.', outcome: 'Cleaner workload boundaries' },
    { icon: 'bi-eye', title: 'Monitoring and alerts', text: 'CloudWatch coverage, health signals, alert routing, and escalation expectations.', outcome: 'Faster issue detection' },
    { icon: 'bi-database-check', title: 'Backup architecture', text: 'EC2, RDS, S3, snapshot, and restore expectations tied to business impact.', outcome: 'Clear recovery plan' },
    { icon: 'bi-lock', title: 'Encryption posture', text: 'Data-at-rest and in-transit review for priority workloads and storage.', outcome: 'Better data protection' },
    { icon: 'bi-tags', title: 'Cost tagging', text: 'Budgets, tags, anomaly alerts, and ownership rules for recurring cloud spend.', outcome: 'Fewer billing surprises' },
    { icon: 'bi-box-arrow-up-right', title: 'Deployment hygiene', text: 'Change process, environment separation, and release notes for business apps.', outcome: 'Safer changes' },
    { icon: 'bi-journal-check', title: 'Operations runbooks', text: 'Maintenance, restore, incident, and vendor procedures documented for handoff.', outcome: 'Less tribal knowledge' },
  ],
  infographic: {
    eyebrow: 'Cloud operations model',
    title: 'Secure cloud operations model',
    intro: 'We organize AWS support around the operating controls that keep workloads secure, recoverable, and cost-aware.',
    type: 'ops',
    items: [
      { title: 'Account and identity', text: 'Root account protection, IAM roles, MFA, least privilege, and admin workflow.' },
      { title: 'Network and exposure', text: 'VPC layout, security groups, public services, and segmentation review.' },
      { title: 'Data and recovery', text: 'Backup jobs, snapshots, restore targets, encryption, and retention expectations.' },
      { title: 'Observability', text: 'Logs, alerts, metrics, health checks, and escalation paths.' },
      { title: 'Cost governance', text: 'Budgets, tags, anomaly detection, rightsizing, and ownership reporting.' },
    ],
  },
  problems: [
    { icon: 'bi-currency-dollar', title: 'The bill keeps creeping up', text: 'Unused resources, missing tags, and unclear ownership hide avoidable spend.', outcome: 'We add budgets, tags, and cost review discipline.' },
    { icon: 'bi-key', title: 'Access is too broad', text: 'Admins, users, and service roles have more power than they need.', outcome: 'We map and reduce high-risk permissions.' },
    { icon: 'bi-cloud-slash', title: 'Recovery is assumed, not tested', text: 'Snapshots exist, but restore steps and business targets are unclear.', outcome: 'We document backup coverage and restore paths.' },
  ],
  deliverables: [
    { icon: 'bi-diagram-3', title: 'Cloud architecture diagram', text: 'Account, VPC, workload, and data-flow view for key services.' },
    { icon: 'bi-person-lock', title: 'IAM risk summary', text: 'Privileged users, service roles, MFA gaps, and least-privilege recommendations.' },
    { icon: 'bi-hdd-stack', title: 'Backup and restore notes', text: 'Coverage, retention, restore assumptions, and business recovery gaps.' },
    { icon: 'bi-graph-down-arrow', title: 'Cost-control report', text: 'Budget, tagging, anomaly, and rightsizing recommendations.' },
    { icon: 'bi-bell', title: 'Monitoring matrix', text: 'Alerts, owners, severity, and escalation expectations.' },
    { icon: 'bi-journal-code', title: 'Operations runbook', text: 'Maintenance, incident, release, and recovery procedures.' },
  ],
  engagement: [
    { title: 'Cloud intake', text: 'We collect account structure, workloads, business criticality, and access model.' },
    { title: 'Security and cost review', text: 'We assess IAM, network exposure, backups, monitoring, and billing patterns.' },
    { title: 'Priority remediation', text: 'We close urgent access, exposure, backup, and alerting gaps.' },
    { title: 'Documentation', text: 'We create diagrams and runbooks that make the environment understandable.' },
    { title: 'Operational cadence', text: 'We review cost, alerts, and changes on a recurring schedule.' },
  ],
  scenario: {
    title: 'Small app with unclear AWS ownership',
    problem: 'A business app ran on AWS with no tagging standard, broad IAM access, missing alert routing, and unknown restore steps.',
    fix: 'We documented the architecture, reduced privileged access, added budget alerts, reviewed snapshots, and wrote an incident runbook.',
    outcome: 'The owner could see risk, cost, and recovery assumptions before the next growth push.',
  },
  faq: [
    { question: 'Do you build new AWS environments?', answer: 'Yes, but we usually start by reviewing the business workload, security requirements, recovery expectations, and support model.' },
    { question: 'Can you reduce AWS spend?', answer: 'We can identify waste and set cost guardrails, but savings depend on workload design and business tolerance for changes.' },
    { question: 'Do you support production workloads?', answer: 'We support production operations when monitoring, access, backup, and escalation expectations are clearly defined.' },
    { question: 'Can you work with our developer?', answer: 'Yes. We document ownership boundaries so application code, infrastructure, and support responsibilities are clear.' },
  ],
  relatedLinks: [
    { label: 'Managed IT Services', route: '/managed-it-services' },
    { label: 'Security and Firewall', route: '/security-firewall' },
    { label: 'Crisis Recovery', route: '/crisis-recovery' },
  ],
  finalCta: {
    eyebrow: 'Cloud assessment',
    title: 'Get a clearer AWS operating model before the next outage or bill spike.',
    text: 'Share your account model, key workloads, and backup expectations. We will map the highest-value controls first.',
    primary: { label: 'Request an AWS Assessment', ...consult },
    secondary: { label: 'Review Crisis Recovery', route: '/crisis-recovery' },
  },
};

export const OFFICE_NETWORKING_PAGE: ServiceLandingPage = {
  slug: 'office-networking',
  eyebrow: 'Office networking and Wi-Fi',
  title: 'Build an office network that supports work instead of interrupting it.',
  intro:
    'We design, troubleshoot, document, and secure office networks, Wi-Fi, VLANs, firewalls, switches, printers, VoIP, and ISP handoffs for growing teams.',
  primaryCta: { label: 'Map My Network', ...consult },
  secondaryCta: { label: 'Review Security Controls', route: '/security-firewall' },
  trustChips: ['Wi-Fi troubleshooting', 'VLAN segmentation', 'Office move ready'],
  heroVisual: {
    title: 'Segmented office topology',
    metric: 'Users + guests + voice + devices',
    caption: 'A practical network map that separates sensitive systems, staff devices, guest Wi-Fi, printers, VoIP, and vendor equipment.',
    nodes: ['Staff LAN', 'Guest Wi-Fi', 'VoIP', 'Printers'],
  },
  handleTitle: 'Network work that makes office technology predictable',
  handleIntro: 'Connectivity issues are rarely just the internet. We look at design, cabling, Wi-Fi coverage, switching, firewall rules, and device behavior together.',
  serviceCards: [
    { icon: 'bi-wifi', title: 'Wi-Fi planning', text: 'Coverage review, channel planning, access point placement, and roaming behavior.', outcome: 'Fewer dead zones' },
    { icon: 'bi-router', title: 'Firewall and routing', text: 'Internet handoff, NAT, DHCP, DNS, VPN, and policy review.', outcome: 'Cleaner traffic flow' },
    { icon: 'bi-diagram-3', title: 'VLAN segmentation', text: 'Separate staff, guest, VoIP, printer, server, and device networks where useful.', outcome: 'Reduced lateral risk' },
    { icon: 'bi-ethernet', title: 'Switching and cabling', text: 'Port mapping, switch health, cabling labels, and rack cleanup recommendations.', outcome: 'Faster troubleshooting' },
    { icon: 'bi-printer', title: 'Printer and scanner access', text: 'Stable print paths, scan-to-email checks, and vendor coordination.', outcome: 'Less daily friction' },
    { icon: 'bi-telephone', title: 'VoIP readiness', text: 'Voice VLAN, QoS expectations, ISP coordination, and handoff documentation.', outcome: 'Clearer calls' },
    { icon: 'bi-person-badge', title: 'Guest access', text: 'Visitor Wi-Fi that does not expose business devices or internal systems.', outcome: 'Safer visitor connectivity' },
    { icon: 'bi-map', title: 'Network documentation', text: 'Topology diagrams, port notes, IP ranges, credentials handling, and vendor records.', outcome: 'Less guesswork' },
  ],
  infographic: {
    eyebrow: 'Topology map',
    title: 'Office network topology and VLAN segmentation map',
    intro: 'We turn the network from an undocumented tangle into clear zones with known traffic paths and ownership.',
    type: 'topology',
    items: [
      { title: 'Internet and firewall edge', text: 'ISP handoff, firewall rules, DHCP/DNS, and remote access paths.' },
      { title: 'Core switching', text: 'Switch uplinks, port roles, PoE needs, and cabinet cleanup.' },
      { title: 'Staff network', text: 'Trusted workstations, laptops, file access, and business applications.' },
      { title: 'Guest and IoT networks', text: 'Visitor Wi-Fi, cameras, printers, signage, and vendor-managed devices.' },
      { title: 'Voice and business-critical paths', text: 'VoIP, payment, clinical, or production traffic that needs extra care.' },
    ],
  },
  problems: [
    { icon: 'bi-wifi-off', title: 'Wi-Fi is fine in one room and terrible in another', text: 'Coverage, interference, and roaming issues create uneven staff experience.', outcome: 'We map signal behavior and tune placement.' },
    { icon: 'bi-question-diamond', title: 'No one knows what is plugged in', text: 'Old switches, mystery cables, and unlabeled ports slow every fix.', outcome: 'We document ports, uplinks, and network zones.' },
    { icon: 'bi-printer-fill', title: 'Printers keep breaking workflows', text: 'Print and scan issues often involve DNS, mail, permissions, and vendor defaults.', outcome: 'We stabilize the path and document support ownership.' },
  ],
  deliverables: [
    { icon: 'bi-diagram-3', title: 'Network topology diagram', text: 'Firewall, switches, access points, VLANs, ISP, and key connected systems.' },
    { icon: 'bi-list-columns', title: 'Port and device inventory', text: 'Switch ports, access points, printers, network devices, and ownership notes.' },
    { icon: 'bi-wifi', title: 'Wi-Fi findings', text: 'Coverage, interference, roaming, and access point recommendations.' },
    { icon: 'bi-shield-check', title: 'Segmentation plan', text: 'Recommended network zones and traffic boundaries.' },
    { icon: 'bi-telephone-inbound', title: 'Vendor escalation notes', text: 'ISP, VoIP, printer, firewall, and cabling contact paths.' },
    { icon: 'bi-journal-check', title: 'Network runbook', text: 'Common troubleshooting steps and change procedures.' },
  ],
  engagement: [
    { title: 'Site and pain-point review', text: 'We collect floor plan context, user complaints, ISP details, and known equipment.' },
    { title: 'Discovery and mapping', text: 'We map network devices, uplinks, IP ranges, Wi-Fi, and critical systems.' },
    { title: 'Design recommendations', text: 'We define segmentation, Wi-Fi, switching, firewall, and vendor changes.' },
    { title: 'Implementation support', text: 'We coordinate changes with staff impact and rollback expectations.' },
    { title: 'Documentation handoff', text: 'We deliver diagrams, port maps, and support procedures.' },
  ],
  scenario: {
    title: 'Office network after years of small changes',
    problem: 'A clinic had unreliable Wi-Fi, printers on the same network as staff laptops, and no port documentation.',
    fix: 'We mapped switches and access points, separated guest and printer traffic, tuned Wi-Fi coverage, and documented vendor handoffs.',
    outcome: 'Troubleshooting became faster and staff stopped treating connectivity as a daily unknown.',
  },
  faq: [
    { question: 'Do you install cabling?', answer: 'We coordinate cabling requirements and can work with cabling vendors while owning the network design and documentation.' },
    { question: 'Can you fix Wi-Fi without replacing everything?', answer: 'Often yes. We first check placement, interference, firmware, configuration, and access point density.' },
    { question: 'Should a small office use VLANs?', answer: 'Many should separate guest, staff, printer, voice, and sensitive systems, but the design should stay manageable.' },
    { question: 'Can you support an office move?', answer: 'Yes. Network mapping, ISP coordination, Wi-Fi planning, and cutover runbooks are especially useful during moves.' },
  ],
  relatedLinks: [
    { label: 'Office Relocation', route: '/office-it-relocation' },
    { label: 'Managed IT Services', route: '/managed-it-services' },
    { label: 'Security and Firewall', route: '/security-firewall' },
  ],
  finalCta: {
    eyebrow: 'Network map',
    title: 'Stop guessing what is wrong with the office network.',
    text: 'Share your location size, user count, Wi-Fi pain points, and current equipment. We will map the right next step.',
    primary: { label: 'Map My Network', ...consult },
    secondary: { label: 'Plan an Office Move', route: '/office-it-relocation' },
  },
};

export const CRISIS_RECOVERY_PAGE: ServiceLandingPage = {
  slug: 'crisis-recovery',
  eyebrow: 'IT crisis recovery and hardening',
  title: 'Recover from outages and incidents with a plan, not panic.',
  intro:
    'We help offices respond to ransomware concerns, account compromise, server failure, failed updates, email disruption, and vendor outages while documenting what to fix after the emergency.',
  primaryCta: { label: 'Plan My Recovery Path', ...consult },
  secondaryCta: { label: 'Review Security Readiness', route: '/security-firewall' },
  trustChips: ['Incident triage', 'Restore validation', 'Post-incident hardening'],
  heroVisual: {
    title: 'Incident response timeline',
    metric: 'Triage to hardening',
    caption: 'A clear recovery sequence: contain, communicate, restore, verify, and improve controls after the immediate crisis.',
    nodes: ['Contain', 'Restore', 'Verify', 'Harden'],
  },
  handleTitle: 'Recovery support that keeps the business moving',
  handleIntro: 'The first goal is safe restoration. The second is making sure the same failure does not come back next month.',
  serviceCards: [
    { icon: 'bi-life-preserver', title: 'Emergency triage', text: 'Assess what is down, what is risky, and which systems must be protected first.', outcome: 'Clear first steps' },
    { icon: 'bi-shield-lock', title: 'Containment planning', text: 'Account disablement, device isolation, remote access review, and evidence preservation.', outcome: 'Reduced spread' },
    { icon: 'bi-database-up', title: 'Restore coordination', text: 'Backup location review, restore path validation, vendor coordination, and priority order.', outcome: 'Safer recovery' },
    { icon: 'bi-envelope-exclamation', title: 'Email and identity recovery', text: 'Compromised mailbox review, MFA reset, risky rules, and admin access checks.', outcome: 'Account control restored' },
    { icon: 'bi-pc-display', title: 'Endpoint cleanup', text: 'Device health review, patching, protection status, and rebuild recommendations.', outcome: 'Cleaner devices' },
    { icon: 'bi-people', title: 'Leadership communication', text: 'Plain-English status updates, risk notes, next actions, and vendor handoff.', outcome: 'Less confusion' },
    { icon: 'bi-clipboard2-check', title: 'Post-incident review', text: 'Root cause notes, gaps found, and remediation plan.', outcome: 'Better resilience' },
    { icon: 'bi-journal-medical', title: 'Recovery runbooks', text: 'Documented steps for the next outage, account incident, or restore event.', outcome: 'Faster next response' },
  ],
  infographic: {
    eyebrow: 'Response timeline',
    title: 'Incident response timeline',
    intro: 'During a crisis, sequence matters. We separate emergency actions from recovery and post-incident hardening.',
    type: 'timeline',
    items: [
      { label: '0-2h', title: 'Triage', text: 'Identify affected systems, business impact, and immediate safety concerns.' },
      { label: '2-6h', title: 'Contain', text: 'Isolate devices, secure accounts, stop exposed access, and preserve evidence.' },
      { label: '6-24h', title: 'Restore', text: 'Recover priority services using verified backups or vendor-supported paths.' },
      { label: '24-72h', title: 'Verify', text: 'Confirm access, data integrity, mail flow, endpoint health, and user workflows.' },
      { label: 'After', title: 'Harden', text: 'Document root causes and implement controls that reduce repeat incidents.' },
    ],
  },
  problems: [
    { icon: 'bi-clock-history', title: 'No one knows the restore order', text: 'Email, files, line-of-business apps, and phones all feel urgent.', outcome: 'We define recovery priority by business impact.' },
    { icon: 'bi-person-exclamation', title: 'Mailbox compromise is spreading', text: 'Forwarding rules, risky sessions, and reused passwords create ongoing exposure.', outcome: 'We regain account control and review identity gaps.' },
    { icon: 'bi-hdd-rack', title: 'The server failed and backups are unclear', text: 'The office has backups but no recent restore evidence.', outcome: 'We verify recovery options and document gaps.' },
  ],
  deliverables: [
    { icon: 'bi-clipboard2-pulse', title: 'Crisis action log', text: 'What happened, what was changed, and what remains unresolved.' },
    { icon: 'bi-diagram-3', title: 'Affected systems map', text: 'Users, devices, accounts, apps, vendors, and dependencies involved.' },
    { icon: 'bi-database-check', title: 'Restore findings', text: 'Backup coverage, restore evidence, gaps, and next validation steps.' },
    { icon: 'bi-shield-exclamation', title: 'Risk remediation plan', text: 'Priority hardening actions after the immediate recovery.' },
    { icon: 'bi-megaphone', title: 'Communication notes', text: 'Plain-English updates for leadership, staff, and vendor coordination.' },
    { icon: 'bi-journal-check', title: 'Recovery runbook', text: 'Documented procedure for future outage or incident handling.' },
  ],
  engagement: [
    { title: 'Immediate triage', text: 'We gather symptoms, business impact, affected systems, and current access.' },
    { title: 'Containment and safety', text: 'We protect accounts, devices, remote access, and backups before deeper changes.' },
    { title: 'Recovery execution', text: 'We coordinate restore actions and verify priority workflows.' },
    { title: 'Root cause review', text: 'We identify the likely source, missed controls, and remaining risks.' },
    { title: 'Hardening plan', text: 'We turn findings into a practical remediation backlog.' },
  ],
  scenario: {
    title: 'Compromised mailbox during a busy week',
    problem: 'A manager mailbox began sending suspicious messages while staff were also locked out by repeated password resets.',
    fix: 'We revoked sessions, reset MFA, removed inbox rules, reviewed admin access, checked mail flow, and documented follow-up controls.',
    outcome: 'The office regained control and had a clear list of identity and email changes to prevent repeat compromise.',
  },
  faq: [
    { question: 'Do you offer emergency response?', answer: 'We can help triage and coordinate recovery, but scope depends on access, severity, and whether specialist legal or forensic support is required.' },
    { question: 'Can you recover data?', answer: 'We can coordinate restoration from available backups and vendors. Recovery depends on backup quality, retention, and system condition.' },
    { question: 'Should we shut everything down?', answer: 'Not without context. Containment decisions should consider evidence, business impact, and whether backups or systems could be harmed.' },
    { question: 'What happens after the crisis?', answer: 'We document what happened, what changed, and which hardening steps should be prioritized.' },
  ],
  relatedLinks: [
    { label: 'Security and Firewall', route: '/security-firewall' },
    { label: 'Managed IT Services', route: '/managed-it-services' },
    { label: 'Microsoft 365 Support', route: '/microsoft-365' },
  ],
  finalCta: {
    eyebrow: 'Recovery planning',
    title: 'Create a recovery path before the next outage forces one.',
    text: 'Tell us what failed, what systems matter most, and what backup or vendor information you have. We will help sequence the next steps.',
    primary: { label: 'Plan My Recovery Path', ...consult },
    secondary: { label: 'Book a Security Review', route: '/security-firewall' },
  },
};

export const AI_INTEGRATION_PAGE: ServiceLandingPage = {
  slug: 'ai-integration',
  eyebrow: 'AI integration for real operations',
  title: 'Automate the repetitive work without losing control of the business process.',
  intro:
    'We design practical AI workflows for booking, intake, quoting, support, routing, and back-office tasks using secure integrations, human handoff, monitoring, and clear business rules.',
  primaryCta: { label: 'Map an Automation Workflow', ...consult },
  secondaryCta: { label: 'See Web Development', route: '/web-development' },
  trustChips: ['Workflow-first AI', 'Human handoff', 'Secure tool access'],
  heroVisual: {
    title: 'Workflow automation architecture',
    metric: 'AI + tools + guardrails',
    caption: 'AI is useful when it connects to the right systems with permissions, validation, logging, and escalation paths.',
    nodes: ['Voice', 'Chat', 'CRM', 'Payments'],
  },
  handleTitle: 'AI integrations that connect to how your office already works',
  handleIntro: 'We focus on operational workflows where automation can reduce staff load without creating uncontrolled black boxes.',
  serviceCards: [
    { icon: 'bi-mic', title: 'Voice agents', text: 'Phone-based booking, intake, triage, and routing with natural-language handling.', outcome: 'Fewer missed calls' },
    { icon: 'bi-chat-dots', title: 'Chat workflows', text: 'Website or internal chat that collects structured details and triggers next steps.', outcome: 'Cleaner intake' },
    { icon: 'bi-tools', title: 'Tool-calling pipelines', text: 'AI that can look up records, create tasks, update bookings, and call approved APIs.', outcome: 'Real workflow action' },
    { icon: 'bi-person-check', title: 'Human handoff', text: 'Escalation rules for sensitive requests, uncertainty, frustration, or approvals.', outcome: 'Staff stays in control' },
    { icon: 'bi-shield-lock', title: 'Access guardrails', text: 'Scoped permissions, audit logs, rate limits, and data-handling boundaries.', outcome: 'Lower automation risk' },
    { icon: 'bi-diagram-3', title: 'System integration', text: 'CRM, booking, payment, maps, email, spreadsheet, and database connections.', outcome: 'Less duplicate entry' },
    { icon: 'bi-speedometer2', title: 'Cost controls', text: 'Hybrid logic that avoids expensive model calls for simple repeatable answers.', outcome: 'Predictable usage' },
    { icon: 'bi-clipboard2-data', title: 'Monitoring', text: 'Conversation review, failure tracking, and workflow improvement loops.', outcome: 'Better automation over time' },
  ],
  infographic: {
    eyebrow: 'Automation architecture',
    title: 'Workflow automation architecture',
    intro: 'A useful AI workflow has channels, context, tools, rules, logging, and escalation. We design all of those parts together.',
    type: 'automation',
    items: [
      { title: 'Input channels', text: 'Phone, chat, SMS, forms, email, or internal staff requests.' },
      { title: 'Business context', text: 'Policies, pricing rules, service areas, availability, customer records, and constraints.' },
      { title: 'AI decision layer', text: 'Intent detection, structured extraction, response generation, and validation.' },
      { title: 'Approved tools', text: 'Booking, CRM, payments, maps, ticketing, calendar, or database actions.' },
      { title: 'Human oversight', text: 'Escalation, audit logs, approvals, and continuous improvement.' },
    ],
  },
  problems: [
    { icon: 'bi-telephone-x', title: 'Calls are missed or rushed', text: 'Staff are busy and basic intake takes time away from higher-value work.', outcome: 'We automate first-pass capture and routing.' },
    { icon: 'bi-copy', title: 'Data gets retyped across systems', text: 'Forms, emails, spreadsheets, and booking tools do not share clean workflows.', outcome: 'We connect systems through approved actions.' },
    { icon: 'bi-robot', title: 'AI experiments never reach production', text: 'Demos work, but lack permissions, fallback, logging, and cost controls.', outcome: 'We build deployable workflows with guardrails.' },
  ],
  deliverables: [
    { icon: 'bi-diagram-3', title: 'Workflow architecture', text: 'Channels, tools, data sources, guardrails, and escalation paths.' },
    { icon: 'bi-list-check', title: 'Business rules document', text: 'What the AI can do, cannot do, and when it must hand off.' },
    { icon: 'bi-plug', title: 'Integration map', text: 'APIs, databases, booking systems, payments, and operational dependencies.' },
    { icon: 'bi-shield-check', title: 'Security notes', text: 'Permission scopes, data retention, logging, and sensitive data handling.' },
    { icon: 'bi-graph-up', title: 'Monitoring report', text: 'Failure modes, usage, handoffs, and improvement recommendations.' },
    { icon: 'bi-journal-code', title: 'Handoff runbook', text: 'How to operate, review, update, and safely pause the workflow.' },
  ],
  engagement: [
    { title: 'Workflow discovery', text: 'We map the repetitive task, users, systems, edge cases, and business rules.' },
    { title: 'Architecture proposal', text: 'We define channels, model use, integrations, guardrails, and handoff points.' },
    { title: 'Prototype with real data paths', text: 'We validate the workflow with constrained actions and visible logs.' },
    { title: 'Production build', text: 'We harden permissions, monitoring, prompts, costs, and escalation.' },
    { title: 'Launch and improve', text: 'We review conversations and outcomes to refine the workflow safely.' },
  ],
  scenario: {
    title: 'Booking workflow that handles calls and chat',
    problem: 'A service business needed customers to ask questions, estimate pricing, and book without staff copying details between tools.',
    fix: 'We designed an AI intake workflow with structured extraction, map lookup, booking tool actions, payment handoff, and staff escalation.',
    outcome: 'Simple requests could be captured consistently while unusual cases still reached a person.',
  },
  faq: [
    { question: 'Do we need a custom model?', answer: 'Usually no. Most small-business workflows need strong architecture, clean tools, good rules, and monitoring before custom model work.' },
    { question: 'Can AI access our business systems?', answer: 'Yes, but only through scoped, approved integrations with logging, validation, and clear limits.' },
    { question: 'How do you prevent bad answers?', answer: 'We constrain the workflow with business rules, retrieval context, structured outputs, fallback responses, and human handoff.' },
    { question: 'Is this only for customer-facing chat?', answer: 'No. Internal intake, triage, reporting, quoting, and admin workflows can also be good candidates.' },
  ],
  relatedLinks: [
    { label: 'Web Development', route: '/web-development' },
    { label: 'AWS Infrastructure', route: '/aws-infrastructure' },
    { label: 'Managed IT Services', route: '/managed-it-services' },
  ],
  finalCta: {
    eyebrow: 'Workflow map',
    title: 'Find the automation that is worth building first.',
    text: 'Share the repetitive workflow, systems involved, and what currently slows staff down. We will map the safest starting point.',
    primary: { label: 'Map an Automation Workflow', ...consult },
    secondary: { label: 'Review Web Development', route: '/web-development' },
  },
};

export const SERVICE_PAGES = {
  managedIt: MANAGED_IT_PAGE,
  securityFirewall: SECURITY_FIREWALL_PAGE,
  microsoft365: MICROSOFT_365_PAGE,
  googleWorkspace: GOOGLE_WORKSPACE_PAGE,
  medicalClinicIt: MEDICAL_CLINIC_IT_PAGE,
  awsInfrastructure: AWS_INFRASTRUCTURE_PAGE,
  officeNetworking: OFFICE_NETWORKING_PAGE,
  crisisRecovery: CRISIS_RECOVERY_PAGE,
  aiIntegration: AI_INTEGRATION_PAGE,
} as const;

